/* Generated By:JJTree: Do not edit this line. ASTParagraph.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.koara;

public
class ASTParagraph extends SimpleNode {
  public ASTParagraph(int id) {
    super(id);
  }

  public ASTParagraph(Koara p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(KoaraVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4dabc9ad89f520b93fe467807d234fc0 (do not edit this line) */
