/* Generated By:JJTree: Do not edit this line. ASTStrong.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.koara;

public
class ASTStrong extends SimpleNode {
  public ASTStrong(int id) {
    super(id);
  }

  public ASTStrong(Koara p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(KoaraVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=220cfb87e14c2dd919093ff6913cd9a9 (do not edit this line) */
