/* Generated By:JavaCC: Do not edit this line. KoaraVisitor.java Version 6.0_1 */
package io.koara;

public interface KoaraVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTDocument node, Object data);
  public Object visit(ASTHeading node, Object data);
  public Object visit(ASTBlockquote node, Object data);
  public Object visit(ASTList node, Object data);
  public Object visit(ASTListItem node, Object data);
  public Object visit(ASTParagraph node, Object data);
  public Object visit(ASTImage node, Object data);
  public Object visit(ASTLink node, Object data);
  public Object visit(ASTText node, Object data);
  public Object visit(ASTStrong node, Object data);
  public Object visit(ASTEm node, Object data);
  public Object visit(ASTLineBreak node, Object data);
}
/* JavaCC - OriginalChecksum=308a0431cbddee428d88d0ee206d3ec9 (do not edit this line) */
