/* Generated By:JJTree&JavaCC: Do not edit this line. KoaraConstants.java */
package io.koara;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KoaraConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMAGE_LABEL = 1;
  /** RegularExpression Id. */
  int ESCAPED_CHAR = 2;
  /** RegularExpression Id. */
  int ASTERISK = 3;
  /** RegularExpression Id. */
  int BACKTICK = 4;
  /** RegularExpression Id. */
  int BACKSLASH = 5;
  /** RegularExpression Id. */
  int CHAR_SEQUENCE = 6;
  /** RegularExpression Id. */
  int DASH = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int EOL = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int LBRACK = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int LT = 15;
  /** RegularExpression Id. */
  int RBRACK = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int SPACE = 18;
  /** RegularExpression Id. */
  int TAB = 19;
  /** RegularExpression Id. */
  int UNDERSCORE = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"image:\"",
    "<ESCAPED_CHAR>",
    "\"*\"",
    "\"`\"",
    "\"\\\\\"",
    "<CHAR_SEQUENCE>",
    "\"-\"",
    "<DIGITS>",
    "\".\"",
    "<EOL>",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"(\"",
    "\"<\"",
    "\"]\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"_\"",
  };

}
