/* Generated By:JavaCC: Do not edit this line. KoaraTreeConstants.java Version 6.0_1 */
package io.koara;

public interface KoaraTreeConstants
{
  public int JJTDOCUMENT = 0;
  public int JJTVOID = 1;
  public int JJTHEADING = 2;
  public int JJTLIST = 3;
  public int JJTLISTITEM = 4;
  public int JJTPARAGRAPH = 5;
  public int JJTLINK = 6;
  public int JJTTEXT = 7;
  public int JJTLINEBREAK = 8;


  public String[] jjtNodeName = {
    "Document",
    "void",
    "Heading",
    "List",
    "ListItem",
    "Paragraph",
    "Link",
    "Text",
    "LineBreak",
  };
}
/* JavaCC - OriginalChecksum=938eef314fa27985d36fc4ab78ce6e17 (do not edit this line) */
