/* Generated By:JavaCC: Do not edit this line. KoaraDefaultVisitor.java Version 6.0_1 */
package io.koara;

public class KoaraDefaultVisitor implements KoaraVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDocument node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParagraph node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTText node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLineBreak node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=ef6f8155e10be227b7c7f7fc97b839bd (do not edit this line) */
