/* Generated By:JavaCC: Do not edit this line. KoaraTreeConstants.java Version 6.0_1 */
package io.koara;

public interface KoaraTreeConstants
{
  public int JJTDOCUMENT = 0;
  public int JJTVOID = 1;
  public int JJTHEADING = 2;
  public int JJTLIST = 3;
  public int JJTLISTITEM = 4;
  public int JJTPARAGRAPH = 5;
  public int JJTIMAGE = 6;
  public int JJTLINK = 7;
  public int JJTTEXT = 8;
  public int JJTSTRONG = 9;
  public int JJTEM = 10;
  public int JJTLINEBREAK = 11;


  public String[] jjtNodeName = {
    "Document",
    "void",
    "Heading",
    "List",
    "ListItem",
    "Paragraph",
    "Image",
    "Link",
    "Text",
    "Strong",
    "Em",
    "LineBreak",
  };
}
/* JavaCC - OriginalChecksum=6e4287fcf5df0328c606f1e6fd3431c7 (do not edit this line) */
